---

# run to mark after password reset training

##
#
- name: Check if mysql is running
  stat: path=/var/run/mysqld/mysqld.pid
  register: service_status_mysql

- name: Check if mariadb is running
  stat: path=/var/run/mariadb/mariadb.pid
  register: service_status_mariadb


- debug:
    msg: "database is running"
  when: (service_status_mysql.stat.exists == true) or (service_status_mariadb.stat.exists == true) 

- debug:
    msg: "database is MIA brown bread dead lost its head"
  when: (service_status_mysql.stat.exists == false) and (service_status_mariadb.stat.exists == false)

##

- name: Check if .my.cnf exists
  stat: path=/root/.my.cnf
  register: password_file

- debug:
    msg: ".my.cnf exists"
  when: password_file.stat.exists == true

- debug:
    msg: ".my.cnf is missing"
  when: password_file.stat.exists == false

##

- name: Check for specific database
  command: mysql -e 'SHOW DATABASES;'
  register: databases
  ignore_errors: True

- debug:
    var: databases.stdout_lines

- debug:
    var: databases.stderr_lines


- debug:
    msg: "database x still exists"
  when: databases.stat.exists == true
  ignore_errors: True

- debug:
    msg: "database x is missing"
  when: databases.stat.exists == false
  ignore_errors: True

- debug:
    msg: "unable to access database"
  when: databases.stderr_lines == true
  ignore_errors: True

  
#- name: Check if you can login to database


#- name: Check if database x still exists

#- name: output marks
